version: "3.8"
services:
  backend:
    container_name: backend
    image: rlafosem/xsearch_backend
    # build:
    #   dockerfile: Dockerfile
    #   context: ./backend
    env_file:
      - ./.env
    depends_on:
      - postgres
      - s3
    ports:
      - 3000:3000

  frontend:
    container_name: frontend
    image:
      rlafosem/xsearch_frontend
    # build:
    #   dockerfile: Dockerfile
    #   context: ./frontend
    environment:
      - HOST=0.0.0.0
      - PORT=5137
    ports:
      - 80:5137
    env_file:
      - ./.env
    depends_on:
      - engine
      - backend

  postgres:
    container_name: postgresDB
    image: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432

  s3:
    image: minio/minio
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - 9011:9011
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_CORS_ALLOW_ORIGIN: "*"
      MINIO_CORS_ALLOW_METHODS: "GET,PUT,POST,DELETE"
      MINIO_CORS_ALLOW_HEADERS: "*"      
    volumes:
      - ../data/s3/storage/minio:/data
    command: server --address ":9010" --console-address ":9011" /data

  engine:
    container_name: engine
    image:
      rlafosem/xsearch_engine
      #build:
      #dockerfile: Dockerfile
      #context: ./engine
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - "standalone"

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ../data/milvus/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ../data/milvus/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.13
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ../data/milvus/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
